import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '../..');
const base = '/flagship-portfolio-v3';
const media = `${base}/media/job-orbit-flight`;
const release = 'https://github.com/Mohamed3042/motion-video-skill/releases/tag/job-orbit-v2.0';
const download = 'https://github.com/Mohamed3042/motion-video-skill/releases/download/job-orbit-v2.0/MK-Job-Orbit-v2-Share-1080p60.mp4';
const escape = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const scenes = [
  ['profile','#ff754d',26,'Your story. Confirmed.','Build a profile from facts you confirm. Review imported evidence before it becomes resume wording.','Review → confirm → export','قصتك. بمعلومات مؤكدة.','ابنِ ملفك من الحقائق التي تؤكدها. راجع الأدلة المستوردة قبل استخدامها في السيرة الذاتية.','راجع ← أكّد ← صدّر'],
  ['globe','#89b7ff',34,'Give your search coordinates.','Explore saved research, place by place. A location sets your research scope; it does not establish work eligibility.','Place → sources → context','امنح بحثك إحداثيات.','استكشف أبحاثك المحفوظة حسب الموقع. اختيار بلد يحدد نطاق البحث، ولا يثبت أهلية العمل.','الموقع ← المصادر ← السياق'],
  ['findings','#74e1ba',42,'Follow the source.','Read the newest observations with their dates and source context. Recheck an opening before applying.','Observation → source → date','اتبع المصدر.','اقرأ أحدث الملاحظات مع تواريخها وسياق مصادرها. أعد التحقق من الوظيفة قبل التقديم.','الملاحظة ← المصدر ← التاريخ'],
  ['focus','#f3f7ff',50,'One role. A clear next step.','Bring the role, its requirements and your evidence into one view. Ordering helps review; it is not a hiring prediction.','Role → evidence → review','وظيفة واحدة. خطوة واضحة.','اجمع الوظيفة ومتطلباتها وأدلتك في عرض واحد. ترتيب النتائج يساعد على المراجعة، ولا يتنبأ بالتوظيف.','الوظيفة ← الأدلة ← المراجعة'],
  ['fit','#ffca8a',58,'Requirements, not predictions.','Separate supported requirements, confirmed mismatches and missing evidence. Missing evidence is not a rejection.','Supported / mismatch / unknown','المتطلبات، لا التوقعات.','ميّز بين المتطلبات المدعومة والتعارض المؤكد والأدلة الناقصة. نقص الدليل لا يعني الرفض.','مدعوم / تعارض / غير معروف'],
  ['nextproof','#ffa6b7',66,'Choose your next proof.','Explore a hypothetical next step. Planning a project does not add a skill to your profile or guarantee an interview.','A scenario, ready for review','اختر دليلك التالي.','استكشف خطوة افتراضية تالية. التخطيط لمشروع لا يضيف مهارة إلى ملفك ولا يضمن مقابلة.','سيناريو قابل للمراجعة'],
  ['market','#6f8cff',74,'See what your research supports.','Compare the evidence you have saved. Undisclosed pay stays unknown, and a sample is never the whole market.','Saved research, visible gaps','شاهد ما تدعمه أبحاثك.','قارن الأدلة التي حفظتها. الراتب غير المعلن يظل مجهولاً، والعينة لا تمثل السوق بأكمله.','أبحاث محفوظة وفجوات واضحة'],
  ['employers','#c9b6ff',82,'Look beyond the job title.','Inspect employer observations through their sources. A published business need does not prove an open vacancy.','Employer → observation → source','انظر أبعد من المسمى الوظيفي.','راجع ملاحظات أصحاب العمل من خلال مصادرها. الاحتياج المنشور لا يثبت وجود وظيفة شاغرة.','صاحب العمل ← الملاحظة ← المصدر'],
  ['engine','#4d7cff',90,'Keep the evidence trail.','Trace a claim to its source, capture date and review status. Reported, verified and rejected mean different things.','Provenance you can inspect','احتفظ بمسار الأدلة.','تتبّع الادعاء إلى مصدره وتاريخ توثيقه وحالة مراجعته. المنقول والمتحقق منه والمرفوض حالات مختلفة.','مصادر يمكنك مراجعتها'],
  ['anywhere','#5ee0e6',98,'Your PC workspace. On your phone.','Open the desktop workspace through a private connection. Keep the PC awake, Orbit running and your private network available.','Same workspace. Private connection.','مساحة حاسوبك. على هاتفك.','افتح مساحة الحاسوب عبر اتصال خاص. أبقِ الحاسوب مستيقظاً وOrbit قيد التشغيل وشبكتك الخاصة متاحة.','نفس المساحة. اتصال خاص.'],
];
const titles = {en:['Profile & resume','The globe','New findings','Job focus','Your fit','Next proof','My market','Employers','Evidence & agents','Yours, everywhere'],ar:['الملف والسيرة الذاتية','الكرة الأرضية','أحدث النتائج','تركيز الوظيفة','مدى الملاءمة','الدليل التالي','سوقي','أصحاب العمل','الأدلة والوكلاء','معك في كل مكان']};
for (const lang of ['en','ar']) {
  const ar = lang === 'ar';
  const t = (en, arabic) => ar ? arabic : en;
  const route = `${base}/${lang}/work/job-orbit/`;
  const chapterNav = scenes.map((s,i)=>`<li><a href="#${s[0]}" data-station="${i}" aria-label="${escape(titles[lang][i])}"><span>${String(i+1).padStart(2,'0')}</span><b>${escape(titles[lang][i])}</b></a></li>`).join('');
  const steps = scenes.map((s,i)=>`<section class="station" id="${s[0]}" data-index="${i}" style="--accent:${s[1]}"><p class="eyebrow"><span>${String(i+1).padStart(2,'0')} / 10</span> ${escape(titles[lang][i])}</p><h2>${escape(s[ar?6:3])}</h2><p class="station-description">${escape(s[ar?7:4])}</p><p class="station-path">${escape(s[ar?8:5])}</p><a class="text-link" href="#film" data-play-at="${s[2]}">${t('Watch this station','شاهد هذه المحطة')} <span aria-hidden="true">↗</span></a></section>`).join('');
  const imageData = scenes.map((s,i)=>({id:s[0],color:s[1],title:titles[lang][i],image:`${media}/${s[0]}.webp`}));
  const page = `<!doctype html>
<html lang="${lang}" dir="${ar?'rtl':'ltr'}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${t('Job Engine Orbit — Your next chapter has coordinates','Job Engine Orbit — لفصلك القادم إحداثيات')} · Mohamed Mahmoud</title>
<meta name="description" content="${t('A scroll journey through Job Orbit: career evidence, saved opportunity research and a useful next step. Includes the two-minute feature film.','رحلة تمرير عبر Job Orbit: أدلة مهنية وأبحاث فرص محفوظة وخطوة تالية مفيدة. تتضمن الفيلم التعريفي لمدة دقيقتين.')}">
<link rel="canonical" href="https://mohamed3042.github.io${route}"><link rel="alternate" hreflang="en" href="https://mohamed3042.github.io${base}/en/work/job-orbit/"><link rel="alternate" hreflang="ar" href="https://mohamed3042.github.io${base}/ar/work/job-orbit/">
<meta name="theme-color" content="#071253"><meta property="og:type" content="website"><meta property="og:title" content="Job Engine Orbit — The Flight"><meta property="og:description" content="${t('Ten stations. One career workspace. Explore the film.','عشر محطات. مساحة مهنية واحدة. استكشف الفيلم.')}"><meta property="og:image" content="https://mohamed3042.github.io${media}/poster.webp"><meta property="og:url" content="https://mohamed3042.github.io${route}"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="${media}/orbit.png"><link rel="preload" href="${media}/fonts/space.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${media}/flight.css">
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'CreativeWork',name:'Job Engine Orbit — The Flight',url:`https://mohamed3042.github.io${route}`,creator:{'@type':'Person',name:'Mohamed Mahmoud'},inLanguage:lang,description:'An illustrated feature tour with fictional sample data.',video:{'@type':'VideoObject',name:'Job Orbit v2 — The Flight',description:'An illustrated ten-station feature tour. Fictional sample data, not a live product recording.',thumbnailUrl:`https://mohamed3042.github.io${media}/poster.webp`,uploadDate:'2026-10-03',duration:'PT2M',contentUrl:download}})}</script>
</head><body>
<a class="skip" href="#journey">${t('Skip to the journey','انتقل إلى الرحلة')}</a>
<header class="site-nav"><a class="portfolio-link" href="${base}/${lang}/"><span class="monogram">MM</span> <span>REFRACTION <i>/ ${t('Selected software','البرمجيات المختارة')}</i></span></a><div class="nav-actions"><button class="motion-toggle" type="button" aria-pressed="false">${t('Motion on','الحركة مفعلة')}</button><a lang="${ar?'en':'ar'}" href="${base}/${ar?'en':'ar'}/work/job-orbit/">${ar?'EN':'العربية'}</a></div></header>
<main>
<section class="hero" id="top"><div class="star-layer" aria-hidden="true"></div><div class="hero-orbit" aria-hidden="true"><div class="orbital-path path-one"></div><div class="orbital-path path-two"></div><div class="orbital-path path-three"></div><img src="${media}/orbit.png" alt="" width="512" height="512" fetchpriority="high"><span class="satellite satellite-one">${t('Evidence','الأدلة')}</span><span class="satellite satellite-two">${t('Direction','الاتجاه')}</span><span class="satellite satellite-three">${t('Your next step','خطوتك التالية')}</span></div>
<div class="hero-copy"><p class="eyebrow"><span class="signal-dot"></span> Job Engine Orbit</p><h1>${t('Your next chapter<br>has <em>coordinates.</em>','لفصلك القادم<br><em>إحداثيات.</em>')}</h1><p class="hero-description">${t('Turn a noisy job hunt into a workspace for your evidence, your research and your next move.','حوّل ضوضاء البحث عن وظيفة إلى مساحة لأدلتك وأبحاثك وخطوتك القادمة.')}</p><div class="hero-actions"><a class="button primary" href="#journey">${t('Explore the orbit','استكشف المدار')} <span aria-hidden="true">↓</span></a><a class="button film-button" href="#film" data-play-at="0"><span class="play-icon" aria-hidden="true">▶</span> ${t('Watch the film','شاهد الفيلم')} <small>02:00</small></a></div></div>
<div class="hero-foot"><span>${t('CAREER INTELLIGENCE / LOCAL WORKSPACE','ذكاء مهني / مساحة محلية')}</span><span>${t('SCROLL TO FIND YOUR DIRECTION','مرّر لتجد اتجاهك')} <b aria-hidden="true">↓</b></span></div></section>
<section class="intro"><p class="eyebrow">${t('The Flight / Ten stations','الرحلة / عشر محطات')}</p><h2>${t('A better question<br>at every stop.','سؤال أفضل<br>في كل محطة.')}</h2><div><p>${t('What do I know? Where should I look? What evidence is missing? Move through ten connected views, with the source always within reach.','ماذا أعرف؟ أين أبحث؟ ما الأدلة الناقصة؟ تنقّل بين عشرة عروض مترابطة، مع بقاء المصدر في متناولك.')}</p><p class="sample-note">${t('Film illustrations with fictional sample data.','رسوم توضيحية من الفيلم ببيانات نموذجية خيالية.')}</p></div></section>
<div class="journey" id="journey"><div class="flight-viewport"><div class="flight-panel"><div class="flight-caption"><span><i class="signal-dot"></i> ${t('THE ORBIT / FEATURE TOUR','المدار / جولة الميزات')}</span><span class="station-counter">01 / 10</span></div><div class="flight-picture"><img class="frame frame-current" src="${media}/profile.webp" alt="${escape(titles[lang][0])} — ${t('illustrated film frame','إطار توضيحي من الفيلم')}" width="1600" height="900"><img class="frame frame-next" alt="" width="1600" height="900" aria-hidden="true"><div class="frame-edge" aria-hidden="true"></div></div><div class="flight-footer"><span class="current-title">${escape(titles[lang][0])}</span><span class="sample-label">${t('ILLUSTRATED / SAMPLE DATA','توضيحي / بيانات نموذجية')}</span></div><ol class="station-nav" aria-label="${t('Feature stations','محطات الميزات')}">${chapterNav}</ol><div class="flight-progress" aria-hidden="true"><span></span></div></div></div><div class="stations">${steps}</div></div>
<section class="film-section" id="film"><div class="film-heading"><div><p class="eyebrow">${t('Job Orbit v2 / The Flight','Job Orbit v2 / الرحلة')}</p><h2>${t('Take the full flight.','شاهد الرحلة كاملة.')}</h2></div><p>${t('Two minutes. Ten worlds.<br>One continuous camera journey.','دقيقتان. عشرة عوالم.<br>رحلة كاميرا واحدة متصلة.')}</p></div><div class="film-player"><video controls playsinline preload="none" poster="${media}/poster.webp" aria-label="${t('Job Orbit feature film','الفيلم التعريفي لـ Job Orbit')}"></video><button type="button" class="film-cover"><span class="large-play" aria-hidden="true">▶</span><span>${t('Play the film','تشغيل الفيلم')} <small>1080p · 60 fps · 02:00</small></span></button></div><div class="film-links"><p>${t('Original soundtrack. Best with sound.','موسيقى أصلية. التجربة أفضل مع الصوت.')}</p><a class="text-link" href="${release}">${t('Download film & editable source','تنزيل الفيلم والمصدر القابل للتحرير')} ↗</a></div></section>
<section class="evidence-note"><p class="eyebrow">${t('Evidence before action','الدليل قبل الإجراء')}</p><h2>${t('Research with evidence.<br>Applications require review<br>and authorization.','بحث قائم على الأدلة.<br>التقديم يتطلب المراجعة<br>والتفويض.')}</h2><div><p>${t('The film simplifies related desktop and web workflows. Its interfaces illustrate the product; they are not live recordings or proof of a completed application.','يبسّط الفيلم مسارات مترابطة على الحاسوب والويب. واجهاته توضح المنتج، وليست تسجيلات مباشرة أو دليلاً على إتمام تقديم.')}</p><p>${t('The workspace is local by default. Optional AI, search and backup services can send selected data outside the device. Phone access uses the desktop service through your private network.','المساحة محلية افتراضياً. قد ترسل خدمات الذكاء الاصطناعي والبحث والنسخ الاحتياطي الاختيارية بيانات مختارة خارج الجهاز. يستخدم الهاتف خدمة الحاسوب عبر شبكتك الخاصة.')}</p><a class="text-link" href="https://github.com/Mohamed3042/motion-video-skill/blob/job-orbit-v2/docs/job-orbit/PRODUCT-TRUTH.md">${t('Read the feature and claim notes','اقرأ ملاحظات الميزات والادعاءات')} ↗</a></div></section>
</main><footer><a href="${base}/${lang}/production/#project-job-engine-desktop">← ${t('Back to software notes','العودة إلى توثيق البرمجيات')}</a><span>Mohamed Mahmoud · ${t('Kuwait','الكويت')}</span><a href="#top">${t('Back to orbit','العودة إلى المدار')} ↑</a></footer>
<script id="flight-data" type="application/json">${JSON.stringify({scenes:imageData,download,lang})}</script><script src="${media}/flight.js" defer></script>
</body></html>`;
  const destination = path.join(root,lang,'work/job-orbit');
  mkdirSync(destination,{recursive:true});
  writeFileSync(path.join(destination,'index.html'),page);
}
const sitemapPath = path.join(root,'sitemap-0.xml');
let sitemap = readFileSync(sitemapPath,'utf8');
for (const lang of ['en','ar']) {
  const url = `https://mohamed3042.github.io${base}/${lang}/work/job-orbit/`;
  if (!sitemap.includes(`<loc>${url}</loc>`)) {
    const alternatives = ['en','ar'].map(locale=>`<xhtml:link rel="alternate" hreflang="${locale}" href="https://mohamed3042.github.io${base}/${locale}/work/job-orbit/"/>`).join('');
    sitemap=sitemap.replace('</urlset>',`<url><loc>${url}</loc>${alternatives}</url></urlset>`);
  }
}
writeFileSync(sitemapPath,sitemap);
console.log('Built English and Arabic Job Orbit pages and added their sitemap entries.');
